### ISSUE TITLE
fatal error: Unable to locate credentials

### ISSUE THREAD

**Issue by zkk-967** [danny305/MutComputeX#1]
Hi,
When I download the model, I was reminded that I need credentials. Can you provide me with a key？

**Comment by danny305** [comment]
Sorry. Just now seeing this. If you  add `--no-sign-request` to the copy command it should work:
```bash
aws s3 cp --no-sign-request s3://mutcomputex/data/norbelladine_4OMTase/boxes/4OMTase_dataset.pkl .
```

Ill make the change on my end too.
